"use client";

import { motion } from "framer-motion";
import SectionHeader from "./ui/SectionHeader";
import Card from "./ui/Card";

const features = [
  {
    icon: "🌊",
    title: "Story-Driven Water Play",
    description:
      "Every splash is part of a larger narrative. Themed zones reveal chapters of the Minecraft world's story as families explore together.",
  },
  {
    icon: "🌴",
    title: "Tropical Minecraft Biome Environment",
    description:
      "Lush pixel-art jungle meets Hawaiian tropical design — a breathtaking fusion of Aulani's island setting and Minecraft's iconic world-building.",
  },
  {
    icon: "👨‍👩‍👧‍👦",
    title: "Family Exploration at Every Pace",
    description:
      "Calm shoreline zones for toddlers, gentle waves for families, and dynamic surge for older adventurers. Everyone finds their perfect wave.",
  },
  {
    icon: "🏛️",
    title: "Iconic Central Waterpark Temple",
    description:
      "A towering geometric temple structure rises from the center of the dome, serving as the architectural crown jewel and primary photo moment.",
  },
  {
    icon: "🤝",
    title: "Shared Parent-Child Participation",
    description:
      "Designed so parents and kids experience the magic together — no age-segregated queues, no watching from the sidelines. This is family water adventure.",
  },
];

export default function WhatIsSection() {
  return (
    <section id="overview" className="py-20 lg:py-28 bg-[#F8FFFE]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center">
          <SectionHeader
            eyebrow="The Attraction"
            title="What Is the Minecraft Wave Dome?"
            description="A first-of-its-kind indoor aquatic attraction that combines the creativity and wonder of Minecraft with the immersive storytelling magic of Disney — all nestled within the paradise of Aulani, A Disney Resort & Spa in Ko Olina, Hawaiʻi."
          />

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="mt-8 max-w-3xl text-center"
          >
            <p className="text-base sm:text-lg text-[#0A1628]/60 leading-relaxed">
              Step beneath a towering geometric dome and into a living Minecraft
              world. Waves generated by cutting-edge technology ripple through
              biome-themed zones, each with its own story, texture, and level of
              water intensity. Whether your family prefers calm shoreline wading
              or dynamic surf-style waves, the Minecraft Wave Dome has a
              perfectly calibrated experience waiting for you.
            </p>
          </motion.div>
        </div>

        <div className="mt-16 grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <Card key={feature.title} variant="default" delay={index * 0.1}>
              <div className="flex flex-col gap-4">
                <span className="text-4xl" role="img" aria-label={feature.title}>
                  {feature.icon}
                </span>
                <h3 className="text-lg font-bold text-[#0A1628]">
                  {feature.title}
                </h3>
                <p className="text-sm text-[#0A1628]/60 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            </Card>
          ))}

          {/* Wide card spanning full width on large screens */}
          <div className="sm:col-span-2 lg:col-span-3">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: 0.5 }}
              className="rounded-2xl p-8 bg-gradient-to-r from-[#0E4D8B] to-[#1B6CA8] text-white"
            >
              <div className="flex flex-col lg:flex-row items-start lg:items-center gap-6">
                <div className="text-5xl" aria-hidden="true">💎</div>
                <div className="flex-1">
                  <h3 className="text-xl font-bold mb-2">
                    Aulani's Newest Signature Experience
                  </h3>
                  <p className="text-white/80 leading-relaxed">
                    The Minecraft Wave Dome joins Aulani's celebrated lineup of
                    world-class aquatic experiences — from the Waikolohe Valley
                    snorkeling pool to the Ko Olina lagoon. It represents the
                    next chapter in Aulani's story: where beloved global brands
                    meet authentic Hawaiian hospitality in an experience no other
                    resort on earth can offer.
                  </p>
                </div>
                <a
                  href="#features"
                  className="shrink-0 px-6 py-3 bg-[#00B5C5] hover:bg-[#00D4E8] text-white font-semibold text-sm rounded-xl transition-colors"
                >
                  Explore Features →
                </a>
              </div>
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  );
}
